### ISSUE TITLE
3dtool.py won’t convert files from 3D.bsa

### ISSUE THREAD

**Issue by Elsweyr** [ariscop/battlespire-tools#1]
3dtool.py won’t convert any .3D files from 3D.bsa here’s the output, Same result after applying >1CHAMBER.ply at the end.

python.exe 3dtool.py 1CHAMBER.3D
ply
format ascii 1.0
element vertex 0
property int x
property int y
property int z
element face 0
property list uchar int vertex_index
end_header

**Comment by ariscop** [comment]
I recall there being a few files that were broken and had no geometry, if there's a 1CHAMBER.3D outside of the bsa the game will use that instead
Don't have a copy of battlespire handy right now to check
