### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by minexew** [ariscop/battlespire-tools#2]
Pleaseee!

**Comment by ariscop** [comment]
As in the in-game screenshots? they're raw rgb files
[Battlespire:File Area](https://en.uesp.net/wiki/Battlespire:File_Area) on UESP has a tool for converting them to PCX (batraw.zip), which you can then open with gimp or similar

**Comment by minexew** [comment]
No no, I meant if you had any screenshots of the tools output, exported assets, levels re-imported into blender etc. :)

**Comment by ariscop** [comment]
Not really, the blender import was a horrible mess and i didn't get textures working before moving on to something else
Only one i can find is a view of the first room
![B7Owb3mCYAAwgmI](https://user-images.githubusercontent.com/1522423/74615564-22334e80-5176-11ea-958c-9a08a3870e8e.png)

**Comment by minexew** [comment]
Amazing!
It's always fun when you finally get the format right and reveal the geometry in its naked beauty, isn't it? :)
